# MongoDB の設定
db:
  host: localhost
  port: 27017
  name: db_name
  user: db_username
  pass: db_password

# セッションの設定
session:
  secret: session_secret

# ロガーの設定
logger:
  appenders:
    - type: console
    - type: dateFile
      filename: "logs/densan.log"
      pattern: -yyyy-MM-dd
